List<Map<String, String>> nominalRollList = [
  // Officers (13)
  {'category': 'Officers', 'armyNo': 'PA-43337', 'rank': 'Lt Col', 'name': 'Muhammad Tayyab Ghaznavi', 'cl': 'Pb', 'remarks': 'Commanding Officer'},
  {'category': 'Officers', 'armyNo': 'PA-45571', 'rank': 'Maj', 'name': 'Muhammad Usman Anwar', 'cl': 'Pb', 'remarks': '2IC'},
  {'category': 'Officers', 'armyNo': 'PA-55563', 'rank': 'Maj', 'name': 'Muhammad Azfar Mahmood', 'cl': 'Sdh', 'remarks': 'Battery Commander'},
  {'category': 'Officers', 'armyNo': 'PA-52402', 'rank': 'Maj', 'name': 'Muhammad Umair Asim', 'cl': 'Pb', 'remarks': 'Battery Commander'},
  {'category': 'Officers', 'armyNo': 'PA-56482', 'rank': 'Maj', 'name': 'Muhammad Usman Raza Khan', 'cl': 'Pb', 'remarks': 'Battery Commander'},
  {'category': 'Officers', 'armyNo': 'PA-61131', 'rank': 'Capt', 'name': 'Muhammad Nabeel Ghafoor', 'cl': 'Pb', 'remarks': 'Adjutant'},
  {'category': 'Officers', 'armyNo': 'PA-61755', 'rank': 'Capt', 'name': 'Muhammad Ali', 'cl': 'Pb', 'remarks': 'Quartermaster'},
  {'category': 'Officers', 'armyNo': 'PA-65543', 'rank': 'Capt', 'name': 'Taimoor Ahmed', 'cl': 'Ptn', 'remarks': 'GPO'},
  {'category': 'Officers', 'armyNo': 'PA-66748', 'rank': 'Lt', 'name': 'Muhammad Diayan Akhtar', 'cl': 'Pb', 'remarks': 'GPO'},
  {'category': 'Officers', 'armyNo': 'PA-66674', 'rank': 'Lt', 'name': 'Mohammad Haseeb Niaz', 'cl': 'Pb', 'remarks': 'GPO'},
  {'category': 'Officers', 'armyNo': 'PA-66234', 'rank': 'Lt', 'name': 'Mudasar Ali', 'cl': 'Pb', 'remarks': 'GPO'},
  {'category': 'Officers', 'armyNo': 'PA-67711', 'rank': 'Lt', 'name': 'Asad Ullah', 'cl': 'Ptn', 'remarks': 'Section Commander'},
  {'category': 'Officers', 'armyNo': 'PA-68822', 'rank': '2/Lt', 'name': 'Mohammad Hamza', 'cl': 'Pb', 'remarks': 'Attached'},

  // JCOs (17)
  {'category': 'JCOs', 'armyNo': 'PJO-3099842', 'rank': 'SM', 'name': 'Gnr Sadar Ayub', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3121658', 'rank': 'Sub', 'name': 'Gnr Haq Nawaz', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3106328', 'rank': 'Sub', 'name': 'Gnr Muhammad Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3100038', 'rank': 'Sub', 'name': 'Gnr Ashiq Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3100144', 'rank': 'Sub', 'name': 'TA Mubarak', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3114197', 'rank': 'N/Sub', 'name': 'Gnr Muhammad Naeem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3111230', 'rank': 'N/Sub', 'name': 'Gnr Muhammad Asad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3133462', 'rank': 'N/Sub', 'name': 'Gnr Fazal Wahab', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3117115', 'rank': 'N/Sub', 'name': 'OCU Madad Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3108705', 'rank': 'N/Sub', 'name': 'DMT Bakhtiar Khan', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3141379', 'rank': 'N/Sub', 'name': 'TA Gul Naseem', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3122088', 'rank': 'N/Sub', 'name': 'OCU Tahir Aziz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3096674', 'rank': 'N/Sub', 'name': 'Clk Aziz Muhammad Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3141735', 'rank': 'N/Sub', 'name': 'Gnr Muhammad Zia Ullah', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3141475', 'rank': 'N/Sub', 'name': 'Gnr Tanveer Ahmed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3147263', 'rank': 'N/Sub', 'name': 'Gnr Nadeem Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'JCOs', 'armyNo': 'PJO-3118217', 'rank': 'N/Sub', 'name': 'TA Navaid Asif', 'cl': 'Sdh', 'remarks': ''},

  // Clks (12)
  {'category': 'Clks', 'armyNo': '3122918', 'rank': 'Hav', 'name': 'Clk Bashir Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3138647', 'rank': 'Hav', 'name': 'Clk Muhammad Yasir', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3153363', 'rank': 'Hav', 'name': 'Clk Muhammad Ramzan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3158376', 'rank': 'Hav', 'name': 'Clk Muhammad Shahbaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3158273', 'rank': 'Nk', 'name': 'Clk Muhammad Yasir', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3169371', 'rank': 'Nk', 'name': 'Clk Asif Mehmood', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3192086', 'rank': 'Nk', 'name': 'Clk Muhammad Ilyas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3158329', 'rank': 'Lnk', 'name': 'Clk Shoaib Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3186830', 'rank': 'Clk', 'name': 'Aamir Hayat', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3221173', 'rank': 'Clk', 'name': 'Kashif Wazir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '3221392', 'rank': 'Clk', 'name': 'Asaad Anwar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Clks', 'armyNo': '10207812', 'rank': 'Clk', 'name': 'Aadil Hussain', 'cl': 'Sdh', 'remarks': ''},

  // Svys (12)
  {'category': 'Svys', 'armyNo': '3154456', 'rank': 'BQMH', 'name': 'Svy Ahmed Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3179500', 'rank': 'Hav', 'name': 'Svy Muhammad Idrees', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3156116', 'rank': 'Lhav', 'name': 'Svy Khadman', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3156156', 'rank': 'Nk', 'name': 'Svy Gulfraz Ahmad', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3175231', 'rank': 'Lnk', 'name': 'Svy Wajid Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3177490', 'rank': 'Lnk', 'name': 'Svy Ghulam Sajjad', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3203222', 'rank': 'Svy', 'name': 'Yasir Irfat', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3203142', 'rank': 'Lnk', 'name': 'Svy Faisal Ayub', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3209192', 'rank': 'Svy', 'name': 'Ismaeel Zabeehullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3209817', 'rank': 'Svy', 'name': 'Jamil Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3212484', 'rank': 'Svy', 'name': 'Muhammad Aslam', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Svys', 'armyNo': '3208495', 'rank': 'Svy', 'name': 'Muhammad Jamshed', 'cl': 'Pb', 'remarks': ''},

  // TAs (28)
  {'category': 'TAs', 'armyNo': '3175394', 'rank': 'RQMH', 'name': 'TA Aamir Shahzad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3186474', 'rank': 'Hav', 'name': 'Muhammad Sohail Adnan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3156226', 'rank': 'Hav', 'name': 'TA Younas Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3163228', 'rank': 'Lhav', 'name': 'TA Naveed Iqbal', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3156738', 'rank': 'Lhav', 'name': 'TA Shaista Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3145638', 'rank': 'Hav', 'name': 'TA Parvez Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3187922', 'rank': 'Lhav', 'name': 'TA Muhammad Asif Yousaf', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3156807', 'rank': 'TA', 'name': 'Amjad Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3139629', 'rank': 'Nk', 'name': 'TA Farid Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3188316', 'rank': 'Lnk', 'name': 'TA Abdul Salam', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3187840', 'rank': 'Nk', 'name': 'TA Muhammad Aamir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3192839', 'rank': 'Lnk', 'name': 'TA Muhammad Ashiq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3157112', 'rank': 'Lnk', 'name': 'TA Saif Ur Rehman', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3191300', 'rank': 'Lnk', 'name': 'TA Muhammad Noman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3196939', 'rank': 'Lnk', 'name': 'TA Nasir Mehmood', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3188317', 'rank': 'TA', 'name': 'Muhammad Imran Fareed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3188004', 'rank': 'Lnk', 'name': 'TA Humair Raza Kazmai', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3156623', 'rank': 'TA', 'name': 'Abdul Wahab', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3164739', 'rank': 'TA', 'name': 'Manzoor Elahi', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3177687', 'rank': 'Nk', 'name': 'TA Muhammad Kashif', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3161148', 'rank': 'Lnk', 'name': 'TA Nadeem Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3188615', 'rank': 'Nk', 'name': 'TA Muhammad Asif', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3216620', 'rank': 'TA', 'name': 'Sameed Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3226536', 'rank': 'TA', 'name': 'Muhammad Zesshan Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3227884', 'rank': 'TA', 'name': 'Asad Farooq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3225476', 'rank': 'TA', 'name': 'Javed Akhtar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3215615', 'rank': 'TA', 'name': 'Hazrat Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'TAs', 'armyNo': '3226167', 'rank': 'TA', 'name': 'Ali Husnain', 'cl': 'Pb', 'remarks': ''},

  // OCsU (61)
  {'category': 'OCsU', 'armyNo': '3144778', 'rank': 'RHM Hav', 'name': 'OCU Ghulam Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3125849', 'rank': 'Hav', 'name': 'OCU Sajjad Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3137700', 'rank': 'Hav', 'name': 'OCU Irfan Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3149393', 'rank': 'Hav', 'name': 'OCU Asim Shahzad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3143873', 'rank': 'Lhav', 'name': 'OCU Sajid', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3146799', 'rank': 'Lhav', 'name': 'OCU Rajab Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3139809', 'rank': 'Lhav', 'name': 'OCU Yasir Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3143964', 'rank': 'Lhav', 'name': 'OCU Khawar Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3150628', 'rank': 'Hav', 'name': 'OCU Muhammad Ikram', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3151493', 'rank': 'Nk', 'name': 'OCU Muhammad Ramzan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3162246', 'rank': 'BQMH', 'name': 'OCU Hafiz Muhammad Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3140077', 'rank': 'Nk', 'name': 'OCU Rafee Raza', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3161961', 'rank': 'Nk', 'name': 'OCU Fiaz Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3166548', 'rank': 'NK', 'name': 'OCU Rehman Islam', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3183799', 'rank': 'Nk', 'name': 'OCU Muhammad Waqas Qasim', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3147099', 'rank': 'Nk', 'name': 'OCU Shahid Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3149965', 'rank': 'Nk', 'name': 'OCU Imran Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3186024', 'rank': 'Lnk', 'name': 'OCU Muhammad Naeem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3185727', 'rank': 'Lnk', 'name': 'OCU Muhammad Yousaf', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3186641', 'rank': 'Lnk', 'name': 'OCU Abdul Majeed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3186373', 'rank': 'Lnk', 'name': 'OCU Muhammad Farooq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3185879', 'rank': 'Lnk', 'name': 'OCU Jahan Zeb Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3185749', 'rank': 'Lnk', 'name': 'OCU Muhammad Usman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3154667', 'rank': 'OCU', 'name': 'Jawad Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3190927', 'rank': 'OCU', 'name': 'Muhammad Waseem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3192742', 'rank': 'OCU', 'name': 'Umair Zafar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3193388', 'rank': 'OCU', 'name': 'Hamza Aamir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3203358', 'rank': 'OCU', 'name': 'Shah Zaib', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3208495', 'rank': 'OCU', 'name': 'Faheem Ur Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3208619', 'rank': 'OCU', 'name': 'Adeel Hamza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3160528', 'rank': 'OCU', 'name': 'Majid Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3153929', 'rank': 'OCU', 'name': 'Khazer Hayat', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3156995', 'rank': 'OCU', 'name': 'Ashraf Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3164296', 'rank': 'OCU', 'name': 'Amin Ullah Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3158750', 'rank': 'OCU', 'name': 'Ahmad Jamal Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3158806', 'rank': 'OCU', 'name': 'Akhtar Munir', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3157562', 'rank': 'OCU', 'name': 'Ajaz Ahmad', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3159984', 'rank': 'OCU', 'name': 'Naeem Akhtar', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3154771', 'rank': 'OCU', 'name': 'Taj Afsar', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3161218', 'rank': 'OCU', 'name': 'Waqar Azam', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3199271', 'rank': 'OCU', 'name': 'Muhammad Hamza', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3164394', 'rank': 'OCU', 'name': 'Abdullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3163692', 'rank': 'OCU', 'name': 'Ali Nawaz', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3163725', 'rank': 'OCU', 'name': 'Shoaban Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3167382', 'rank': 'OCU', 'name': 'Shaukat Pervez', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3204267', 'rank': 'OCU', 'name': 'Ahmed Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3204169', 'rank': 'OCU', 'name': 'Rawal', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3210467', 'rank': 'OCU', 'name': 'Fayaz Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3207255', 'rank': 'OCU', 'name': 'Mehtab Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3212811', 'rank': 'OCU', 'name': 'Muhammad Azam', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3213474', 'rank': 'OCU', 'name': 'Raheel Azhar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3215102', 'rank': 'OCU', 'name': 'Muhammad Ijaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3227114', 'rank': 'OCU', 'name': 'Abdullah', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3226439', 'rank': 'OCU', 'name': 'Syed Mehdi Hassan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3225885', 'rank': 'OCU', 'name': 'Islam Nabi', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3160912', 'rank': 'OCU', 'name': 'Shahid Zaheer', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3227936', 'rank': 'OCU', 'name': 'Muhammad Asad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '10200578', 'rank': 'OCU', 'name': 'Muhammad Abdullah', 'cl': 'Pb', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '10200407', 'rank': 'OCU', 'name': 'Madad Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3226725', 'rank': 'OCU', 'name': 'Haseen', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'OCsU', 'armyNo': '3215851', 'rank': 'OCU', 'name': 'Muhammad Bilal', 'cl': 'Pb', 'remarks': ''},

  // DSVs (18)
  {'category': 'DSVs', 'armyNo': '3133766', 'rank': 'Hav', 'name': 'DSV Hubdar Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3135039', 'rank': 'Nk', 'name': 'DSV Farman Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3156337', 'rank': 'Lhav', 'name': 'DSV Sabir Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3191002', 'rank': 'Nk', 'name': 'DSV Muhammad Waqas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3156477', 'rank': 'Nk', 'name': 'DSV Muhammad Hassan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3157723', 'rank': 'Lnk', 'name': 'DSV Naseer Ahmed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3163193', 'rank': 'Lnk', 'name': 'DSV Shabbir Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3178091', 'rank': 'Nk', 'name': 'DSV Mustansar Ashraf', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3191146', 'rank': 'Nk', 'name': 'DSV Shahid Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3206056', 'rank': 'DSV', 'name': 'Iftikhar Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3190600', 'rank': 'Lnk', 'name': 'DSV Arslan Aslam', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3200912', 'rank': 'Nk', 'name': 'DSV Muhammad Adnan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3209649', 'rank': 'DSV', 'name': 'Muhammad Ehsan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3209797', 'rank': 'DSV', 'name': 'Muhammad Arslan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3211151', 'rank': 'DSV', 'name': 'Mujahid Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3227651', 'rank': 'DSV', 'name': 'Sami Ur Rahman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '10200647', 'rank': 'DSV', 'name': 'Wasim Akash', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DSVs', 'armyNo': '3190895', 'rank': 'Lnk', 'name': 'DSV Ali Akbar', 'cl': 'Pb', 'remarks': ''},

  // DMTs (45)
  {'category': 'DMTs', 'armyNo': '3122651', 'rank': 'BQMH', 'name': 'DMT Nasir Aziz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3144453', 'rank': 'Lhav', 'name': 'DMT Muhammad Zubair Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3143670', 'rank': 'Lhav', 'name': 'DMT Akhtar Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3144940', 'rank': 'Lhv', 'name': 'DMT Muhammad Muneer', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3147154', 'rank': 'Hav', 'name': 'DMT Wahid Amin', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3113169', 'rank': 'Hav', 'name': 'DMT Adab Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3142518', 'rank': 'Lhav', 'name': 'DMT Abdul Majid', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3188213', 'rank': 'Nk', 'name': 'DMT Muhammad Faisal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3148579', 'rank': 'Nk', 'name': 'DMT Khalid Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3175362', 'rank': 'Nk', 'name': 'DMT Sajid Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3122617', 'rank': 'Hav', 'name': 'DMT Hijrat Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3145145', 'rank': 'Nk', 'name': 'DMT Sultan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3177469', 'rank': 'Lnk', 'name': 'DMT Muhammad Zubair', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3150343', 'rank': 'Nk', 'name': 'DMT Shafaqat Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3204249', 'rank': 'DMT', 'name': 'Fida Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3145145', 'rank': 'Lhav', 'name': 'DMT Asif Ijaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3190573', 'rank': 'Nk', 'name': 'DMT Muhammad Shahid', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3168497', 'rank': 'Nk', 'name': 'DMT Ishtaiq Ahmad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3190887', 'rank': 'Nk', 'name': 'DMT Muhammad Rizwan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3149630', 'rank': 'Nk', 'name': 'DMT Muhammad Imran', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3168296', 'rank': 'Nk', 'name': 'DMT Muhammad Jehangir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3191021', 'rank': 'Lnk', 'name': 'DMT Shahzad Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3191096', 'rank': 'DMT', 'name': 'Sohail Anjum', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3194636', 'rank': 'DMT', 'name': 'Rashid Minhas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3203623', 'rank': 'DMT', 'name': 'Muhammad Aamir Nazir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3203649', 'rank': 'DMT', 'name': 'Nabeel Raza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3203041', 'rank': 'DMT', 'name': 'Danish Amin Satti', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3203169', 'rank': 'DMT', 'name': 'Zeeshan Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3206125', 'rank': 'DMT', 'name': 'Shahzad Akhtar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3205400', 'rank': 'DMT', 'name': 'Muhammad Kashif', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3205742', 'rank': 'DMT', 'name': 'Muhammad Husnain Raza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3209482', 'rank': 'DMT', 'name': 'Muhammad Hummam Tariq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3209791', 'rank': 'DMT', 'name': 'Ahsan Saeed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3211475', 'rank': 'DMT', 'name': 'Muhammad Asif', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3175395', 'rank': 'DMT', 'name': 'Irfan Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3155018', 'rank': 'DMT', 'name': 'Muhammad Saeed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3178413', 'rank': 'Lnk', 'name': 'Sana Ullah', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3210202', 'rank': 'DMT', 'name': 'Hussain Bakhsh', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3211089', 'rank': 'DMT', 'name': 'Ghulam Mustafa', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3155806', 'rank': 'Lnk', 'name': 'DMT Abdul Latif', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3210236', 'rank': 'DMT', 'name': 'Muhammad Ibrahim', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3212683', 'rank': 'DMT', 'name': 'Muhammad Ahmad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3212297', 'rank': 'DMT', 'name': 'Shaban Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '10203600', 'rank': 'DMT', 'name': 'Muhammad Bilal Saleem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'DMTs', 'armyNo': '3224438', 'rank': 'DMT', 'name': 'Bilal Nasir', 'cl': 'Pb', 'remarks': ''},

  // Gnrs (184)
  {'category': 'Gnrs', 'armyNo': '3137033', 'rank': 'Hav', 'name': 'Gnr Abdul Haq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3141471', 'rank': 'Hav', 'name': 'Gnr Mohsin Raza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3114796', 'rank': 'Hav', 'name': 'Gnr Haji Khan', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3133832', 'rank': 'Hav', 'name': 'Gnr Irfan Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3137481', 'rank': 'Hav', 'name': 'Gnr Ahmed Nawaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142581', 'rank': 'Hav', 'name': 'Gnr Atta Muhammad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3140154', 'rank': 'Hav', 'name': 'Gnr Muhammad Ishaq', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142211', 'rank': 'Hav', 'name': 'Gnr Muhammad Saeed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3144144', 'rank': 'Hav', 'name': 'Gnr Ghalib Hussian', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3150752', 'rank': 'Hav', 'name': 'Gnr Rafaqat Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3140058', 'rank': 'Lhav', 'name': 'Gnr Hamid Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3153938', 'rank': 'Lhav', 'name': 'Gnr Muhammad Irfan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3145523', 'rank': 'Hav', 'name': 'Gnr Muhammad Yasir', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3141879', 'rank': 'Hav', 'name': 'Gnr Abdul Ghafoor', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3179926', 'rank': 'Hav', 'name': 'Gnr Mahboob Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3178590', 'rank': 'BHM', 'name': 'Gnr Muhammad Usman', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156343', 'rank': 'Hav', 'name': 'Gnr Gul Zaman Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3147131', 'rank': 'Hav', 'name': 'Gnr Hasnain Abrar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156846', 'rank': 'BHM', 'name': 'Gnr Shafaqat Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142973', 'rank': 'Hav', 'name': 'Gnr Kamran Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142087', 'rank': 'Lhav', 'name': 'Gnr Abid Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3140212', 'rank': 'Lhav', 'name': 'Gnr Javed Rehman', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3179907', 'rank': 'Nk', 'name': 'Gnr Saeed Ahmad', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3147690', 'rank': 'Nk', 'name': 'Gnr Kamran Yasin', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156600', 'rank': 'Nk', 'name': 'Gnr Muhammad Saeed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156388', 'rank': 'Lhav', 'name': 'Gnr Ghulam Fareed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3166688', 'rank': 'Hav', 'name': 'Gnr Sajid Ur Rehman', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3153713', 'rank': 'BQMH Hav', 'name': 'Gnr Qari Muhammad Fiaz Ahmed Siddiqui', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142535', 'rank': 'Lhav', 'name': 'Gnr Arif Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3166413', 'rank': 'BHM Hav', 'name': 'Gnr Khalid Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3161925', 'rank': 'Lnk', 'name': 'Gnr Baqar Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3184590', 'rank': 'Gnr', 'name': 'Muhammad Arshad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3187487', 'rank': 'Gnr', 'name': 'Nadir Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3186283', 'rank': 'Gnr', 'name': 'Muhammad Zubair', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3135244', 'rank': 'Hav', 'name': 'Gnr Ikram Ullah', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3140061', 'rank': 'Nk', 'name': 'Gnr Ishtiaq Ahmed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3147559', 'rank': 'Nk', 'name': 'Gnr Mubbashir Ramzan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142803', 'rank': 'Nk', 'name': 'Gnr Hafeez Ur Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3144393', 'rank': 'Lhav', 'name': 'Gnr Muhammad Saleem', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3157534', 'rank': 'Lhav', 'name': 'Gnr Asad Mehmood', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3155025', 'rank': 'Nk', 'name': 'Gnr Yasir Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156755', 'rank': 'Nk', 'name': 'Gnr Muhammad Nawazish', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3142086', 'rank': 'Nk', 'name': 'Gnr Abdul Sattar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3158773', 'rank': 'Nk', 'name': 'Gnr Tanveer Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181879', 'rank': 'BHM Hav', 'name': 'Gnr Murad Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181882', 'rank': 'Gnr', 'name': 'Israr Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3160371', 'rank': 'Nk', 'name': 'Khalil Ur Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3160568', 'rank': 'Nk', 'name': 'Gnr Mohsin Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3182077', 'rank': 'Nk', 'name': 'Gnr Ghulam Farooque', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3161070', 'rank': 'Nk', 'name': 'Gnr Amir Muhammad Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3157256', 'rank': 'Nk', 'name': 'Gnr Sardar Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3155659', 'rank': 'Lnk', 'name': 'Gnr Imtiaz Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3147899', 'rank': 'Nk', 'name': 'Gnr Muhammad Kashif Nadeem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3153939', 'rank': 'Nk', 'name': 'Gnr Ajmal Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3154548', 'rank': 'Lnk', 'name': 'Gnr Muhmmad Ikram', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3154626', 'rank': 'Lnk', 'name': 'Gnr Muhammad Uzair', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3157022', 'rank': 'Lnk', 'name': 'Gnr Muddassar Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3164618', 'rank': 'Lnk', 'name': 'Gnr Muhammad Imran', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3166823', 'rank': 'Lnk', 'name': 'Gnr Muhammad Rizwan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3157561', 'rank': 'Lnk', 'name': 'Gnr Abdul Qadoos', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3186434', 'rank': 'Lnk', 'name': 'Gnr Tanveer Anjum', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3159292', 'rank': 'Lnk', 'name': 'Gnr Muhammad Awais', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3186485', 'rank': 'Lnk', 'name': 'Gnr Muhammad Usman', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3157737', 'rank': 'Nk', 'name': 'Gnr Muhammad Kamran', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201323', 'rank': 'Nk', 'name': 'Gnr Faizan Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201635', 'rank': 'Nk', 'name': 'Gnr Taimoor Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201414', 'rank': 'Lnk', 'name': 'Gnr Nadeem', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201098', 'rank': 'Nk', 'name': 'Gnr Adeel Ahmed Khan', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3159553', 'rank': 'Lnk', 'name': 'Gnr Zaheer Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167722', 'rank': 'Lnk', 'name': 'Muhammad Asghar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3155419', 'rank': 'Lnk', 'name': 'Gnr Muhammad Naheem', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3156541', 'rank': 'Lnk', 'name': 'Gnr Muhammad Akram', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3166482', 'rank': 'Lnk', 'name': 'Gnr Majid Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181487', 'rank': 'Gnr', 'name': 'Zafar Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181469', 'rank': 'Gnr', 'name': 'Waleed Ahmad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3180331', 'rank': 'Gnr', 'name': 'Saqib Munir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3183179', 'rank': 'Gnr', 'name': 'Talib Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3177996', 'rank': 'Gnr', 'name': 'Muhammad Maqsood Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181266', 'rank': 'Gnr', 'name': 'Muhammad Imran', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3169750', 'rank': 'Gnr', 'name': 'Shahid Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3168738', 'rank': 'Gnr', 'name': 'Muhammad Saleem', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3166787', 'rank': 'Lnk', 'name': 'Gnr Mukhtar Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181613', 'rank': 'Gnr', 'name': 'Muhammad Asif', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3194535', 'rank': 'Gnr', 'name': 'Muhammad Khawar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3181108', 'rank': 'Gnr', 'name': 'Wahid Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3180593', 'rank': 'Gnr', 'name': 'Shakeel Ahmad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3178003', 'rank': 'Gnr', 'name': 'Wasif Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3184230', 'rank': 'Gnr', 'name': 'Akbar Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3184302', 'rank': 'Gnr', 'name': 'Adeel Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3188887', 'rank': 'Gnr', 'name': 'Muhammad Ikram', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201696', 'rank': 'Gnr', 'name': 'Muhammad Touseef Tariq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3200733', 'rank': 'Gnr', 'name': 'Ali Raza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3200273', 'rank': 'Gnr', 'name': 'Muhammad Musawar', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3200627', 'rank': 'Gnr', 'name': 'Muhammad Israr Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3203867', 'rank': 'Lnk', 'name': 'Gnr Sikandar Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3206604', 'rank': 'Gnr', 'name': 'Abid Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3209731', 'rank': 'Gnr', 'name': 'Muhammad Saqib Mushtaq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3208313', 'rank': 'Gnr', 'name': 'Ahmed Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3205897', 'rank': 'Gnr', 'name': 'Sohail Mushtaq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3206734', 'rank': 'Gnr', 'name': 'Afaaq Zameer', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3209067', 'rank': 'Gnr', 'name': 'Sammar Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3215833', 'rank': 'Gnr', 'name': 'Muhammad Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3163007', 'rank': 'Lnk', 'name': 'Gnr Muhammad Riaz Khan', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167772', 'rank': 'Gnr', 'name': 'Faisal Shahzad', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167928', 'rank': 'Gnr', 'name': 'Imran', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3169699', 'rank': 'Gnr', 'name': 'Ijaz Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3169844', 'rank': 'Gnr', 'name': 'Feesar Mehmood', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3170721', 'rank': 'Gnr', 'name': 'Waqar Saeed', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3163396', 'rank': 'Gnr', 'name': 'Mushtaq', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167512', 'rank': 'Gnr', 'name': 'Ghulab Noor', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3168512', 'rank': 'Gnr', 'name': 'Saadat Ali Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3176395', 'rank': 'Gnr', 'name': 'Umar Hayat', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3160105', 'rank': 'Lnk', 'name': 'Gnr Qamber Hussain Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3160326', 'rank': 'Gnr', 'name': 'Sami Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167026', 'rank': 'Gnr', 'name': 'Shahid Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167105', 'rank': 'Gnr', 'name': 'Syed Majid Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3163378', 'rank': 'Gnr', 'name': 'Abdul Khaliq', 'cl': 'Ptn', 'remarks': 'Fd Inc'},
  {'category': 'Gnrs', 'armyNo': '3161135', 'rank': 'Lnk', 'name': 'Gnr Muhammad Naseer', 'cl': 'Ptn', 'remarks': 'Fd Inc'},
  {'category': 'Gnrs', 'armyNo': '3167254', 'rank': 'Gnr', 'name': 'Aadil', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3167728', 'rank': 'Gnr', 'name': 'Syed Qayyum Shah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204218', 'rank': 'Gnr', 'name': 'Khandad Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3203168', 'rank': 'Gnr', 'name': 'Kamran Hayat', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201495', 'rank': 'Lnk', 'name': 'Gnr Ali Jan', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3188314', 'rank': 'Lnk', 'name': 'Gnr Sikandar Ahemd', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3194674', 'rank': 'Gnr', 'name': 'Muhammad Ahsan', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3201893', 'rank': 'Gnr', 'name': 'Abdul Rehman', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204040', 'rank': 'Lnk', 'name': 'Gnr Zamir Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204204', 'rank': 'Gnr', 'name': 'Wakeel Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204013', 'rank': 'Lnk', 'name': 'Ashfaque Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204274', 'rank': 'Gnr', 'name': 'Awais Ahmed', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3205519', 'rank': 'Gnr', 'name': 'Zafar Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204196', 'rank': 'Gnr', 'name': 'Arif', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3203819', 'rank': 'Gnr', 'name': 'Muhammad Younis', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3204240', 'rank': 'Gnr', 'name': 'Raza Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3213403', 'rank': 'Gnr', 'name': 'Muhammad Asif', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3212601', 'rank': 'Gnr', 'name': 'Aurang Zeb', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3213086', 'rank': 'Gnr', 'name': 'Muhammad Farooq-e-Azam', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3170892', 'rank': 'Gnr', 'name': 'Muhammad Ali', 'cl': 'Pb', 'remarks': 'Fd Inc'},
  {'category': 'Gnrs', 'armyNo': '3167330', 'rank': 'Gnr', 'name': 'Muhammad Akhlaq', 'cl': 'Pb', 'remarks': 'Fd Inc'},
  {'category': 'Gnrs', 'armyNo': '3167565', 'rank': 'Gnr', 'name': 'Muhammad Asif', 'cl': 'Pb', 'remarks': 'Fd Inc'},
  {'category': 'Gnrs', 'armyNo': '3209485', 'rank': 'Gnr', 'name': 'Muhammad Ahmad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3215166', 'rank': 'Gnr', 'name': 'Zia Ul Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3215281', 'rank': 'Gnr', 'name': 'Muhammad Imtiaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3215294', 'rank': 'Gnr', 'name': 'Waqas Khan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216051', 'rank': 'Gnr', 'name': 'Nouman Riaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216062', 'rank': 'Gnr', 'name': 'Malik M. Ramzan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216367', 'rank': 'Gnr', 'name': 'Bilal Hassan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216377', 'rank': 'Gnr', 'name': 'Muzammal Hussain', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216434', 'rank': 'Gnr', 'name': 'Saim Liaqat', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216495', 'rank': 'Gnr', 'name': 'Muhammad Ashraf', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216706', 'rank': 'Gnr', 'name': 'Ali Raza', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216845', 'rank': 'Gnr', 'name': 'Arslan Tariq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216122', 'rank': 'Gnr', 'name': 'Zia Ul Hassan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216858', 'rank': 'Gnr', 'name': 'Fahid Zia', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3217193', 'rank': 'Gnr', 'name': 'Muhammad Jamil', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216850', 'rank': 'Gnr', 'name': 'Mehtab Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3216845', 'rank': 'Gnr', 'name': 'Arslan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3220227', 'rank': 'Gnr', 'name': 'Sami Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3209362', 'rank': 'Gnr', 'name': 'Muqadas Khalid', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3154319', 'rank': 'Gnr', 'name': 'Khizar Hayat', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3223129', 'rank': 'Gnr', 'name': 'Muhammad Azeem Minhas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3226124', 'rank': 'Gnr', 'name': 'Farhan Ijaz', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10201833', 'rank': 'Gnr', 'name': 'Ali Raza', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10201329', 'rank': 'Gnr', 'name': 'Muhammad Morial', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10200314', 'rank': 'Gnr', 'name': 'Abdul Shakoor', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10202005', 'rank': 'Gnr', 'name': 'Kamran Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10200739', 'rank': 'Gnr', 'name': 'Muhammad Usman', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10202118', 'rank': 'Gnr', 'name': 'Zia Ullah', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10201037', 'rank': 'Gnr', 'name': 'Najaf Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3226734', 'rank': 'Gnr', 'name': 'Muhammad Shakeel', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '3226752', 'rank': 'Gnr', 'name': 'Ahmed Ali', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10200830', 'rank': 'Gnr', 'name': 'Sadam Hussain', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10202960', 'rank': 'Gnr', 'name': 'Yasir Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203219', 'rank': 'Gnr', 'name': 'Abdul Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10202724', 'rank': 'Gnr', 'name': 'Hasnain Shabir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10202851', 'rank': 'Gnr', 'name': 'Tauseef Haider', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203391', 'rank': 'Gnr', 'name': 'Usama Razzaq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203831', 'rank': 'Gnr', 'name': 'Muhammad Hassan', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10204281', 'rank': 'Gnr', 'name': 'Muhammad Sajeel', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203573', 'rank': 'Gnr', 'name': 'Syed Kashan Abbas', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203639', 'rank': 'Gnr', 'name': 'Fiaz Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10204016', 'rank': 'Gnr', 'name': 'Mohsin Baber', 'cl': 'Pb', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10203918', 'rank': 'Gnr', 'name': 'Azeem', 'cl': 'Sdh', 'remarks': ''},
  {'category': 'Gnrs', 'armyNo': '10201838', 'rank': 'Gnr', 'name': 'Asad Ali', 'cl': 'Sdh', 'remarks': ''},

  // C/Us / C/Mess (14)
  {'category': 'C/Us', 'armyNo': '3131139', 'rank': 'Hav', 'name': 'Ck U Muhammad Arshad', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3171014', 'rank': 'Nk', 'name': 'C/U Muhammad Shabbir', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3145984', 'rank': 'Nk', 'name': 'C/U Muhammad Ishfaq', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3140350', 'rank': 'Hav', 'name': 'C/U Munir Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3175597', 'rank': 'Lnk', 'name': 'C/U Khurshid Ahmed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3178967', 'rank': 'Lnk', 'name': 'Ck (M) Nasir Hayat', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3196050', 'rank': 'Lnk', 'name': 'C/U Asim Javed', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3175870', 'rank': 'C/U', 'name': 'Amir Hayat', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3140399', 'rank': 'NK', 'name': 'C/U Shahid Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3217268', 'rank': 'C/M', 'name': 'Taimoor Ellahi', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3214142', 'rank': 'Lnk', 'name': 'C/U Asad Ali', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3220765', 'rank': 'C/U', 'name': 'Mazhar Iqbal', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3217110', 'rank': 'C/M', 'name': 'Fazal Ur Rehman', 'cl': 'Pb', 'remarks': ''},
  {'category': 'C/Us', 'armyNo': '3219787', 'rank': 'C/U', 'name': 'Muhammad Irshad', 'cl': 'Pb', 'remarks': ''},

  // SWs (11)
  {'category': 'SWs', 'armyNo': '3165155', 'rank': 'S/W', 'name': 'Liaqat Ali', 'cl': 'Pb', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3186978', 'rank': 'SW', 'name': 'Kamran Masih', 'cl': 'Min', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3165157', 'rank': 'SW', 'name': 'Mazhar Abbas Shah', 'cl': 'Pb', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3172819', 'rank': 'SW', 'name': 'Sadam Hussain', 'cl': 'Ptn', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3189538', 'rank': 'SW', 'name': 'Fakhar Alam', 'cl': 'K&NA', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3214694', 'rank': 'SW', 'name': 'Adam', 'cl': 'Pb', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3172843', 'rank': 'S/W', 'name': 'Mouras Masih', 'cl': 'Min', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3214445', 'rank': 'SW', 'name': 'Yasir Masih', 'cl': 'Min', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3217535', 'rank': 'SW', 'name': 'Chand Masih', 'cl': 'Min', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3172815', 'rank': 'SW', 'name': 'Azam Wali', 'cl': 'K&NA', 'remarks': ''},
  {'category': 'SWs', 'armyNo': '3227386', 'rank': 'SW', 'name': 'Nabeel', 'cl': 'Min', 'remarks': ''},

  // NCBs (12)
  {'category': 'NCBs', 'armyNo': '3174205', 'rank': 'NCB (E)', 'name': 'Tasswar Iqbal', 'cl': 'Pb', 'remarks': 'PA-43337 Lt Col Muhammad Tayyab Ghaznavi'},
  {'category': 'NCBs', 'armyNo': '3224968', 'rank': 'NCB (E)', 'name': 'Shakeel Ahmed', 'cl': 'Pb', 'remarks': 'PA-45571 Maj Muhammad Usman Anwar'},
  {'category': 'NCBs', 'armyNo': '3189883', 'rank': 'NCB (E)', 'name': 'Sajid Ali', 'cl': 'Sdh', 'remarks': 'PA-55563 Maj Muhammad Azfar Mahmood'},
  {'category': 'NCBs', 'armyNo': '3196644', 'rank': 'NCB (E)', 'name': 'Muhammad Rizwan', 'cl': 'Pb', 'remarks': 'PA-52402 Maj Muhammad Umair Asim'},
  {'category': 'NCBs', 'armyNo': '3196699', 'rank': 'NCB (E)', 'name': 'Imran Khan', 'cl': 'Pb', 'remarks': 'PA-56482 Maj Muhammad Usman Raza Khan'},
  {'category': 'NCBs', 'armyNo': '3214801', 'rank': 'NCB (E)', 'name': 'Iftikhar', 'cl': 'Ptn', 'remarks': 'Under Posting'},
  {'category': 'NCBs', 'armyNo': '3217448', 'rank': 'NCB (E)', 'name': 'Muhammad Ayub', 'cl': 'Pb', 'remarks': 'PA-61131 Capt Muhammmad Nabeel Ghafoor'},
  {'category': 'NCBs', 'armyNo': '3214501', 'rank': 'NCB (E)', 'name': 'Ameer Hamza', 'cl': 'Pb', 'remarks': 'PA-61755 Capt Muhammad Ali'},
  {'category': 'NCBs', 'armyNo': '3140729', 'rank': 'NCB (E)', 'name': 'Abdul Latif', 'cl': 'Pb', 'remarks': 'Res'},
  {'category': 'NCBs', 'armyNo': '3224960', 'rank': 'NCB (E)', 'name': 'Muhammad Tehzeeb Arif', 'cl': 'Pb', 'remarks': 'PA-66748 Lt Muhammad Diayan Akhtar'},
  {'category': 'NCBs', 'armyNo': 'NYA', 'rank': 'NCB (E)', 'name': 'Hammad Ali', 'cl': 'Pb', 'remarks': 'PA-66674 Lt Mohammad Haseeb Niaz'},
  {'category': 'NCBs', 'armyNo': 'NYA', 'rank': 'NCB (E)', 'name': 'Muhammad Usman', 'cl': 'Pb', 'remarks': 'PA-66234 Lt Mudasar Ali'},
];
